# -*- coding: utf-8 -*-
"""Week_6_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/

## Week 6 - Assignment
___

"""

class Messenger:
    def __init__(self, user_name, user_phone_number):
      self.user_name = user_name
      self.user_phone_number = user_phone_number
      self.messagebox = []
        # define three variables        


    def info(self):
      print("User : ", self.user_name, "/ Phone number : ", self.user_phone_number)
        # print user name and phone number        
    
    def send(self, target_user, message):
      self.message = message
      target_user.receive(self.message)
        # send a message to target_user        

    def receive(self, message):
      self.message = message
      self.messagebox.append(self.message)
        # receive a message and store the message to the user message box

    def read_latest(self):
      if self.messagebox == []:
        print('empty')
      else:
        print(self.messagebox)

    def read_recent(self , N):
      self.N = N
      if self.messagebox == []:
        print('empty')
      else: 
        print(self.messagebox[len(self.messagebox)-N: ])
    
    def delete(self, option):
      self.option = option
      if option == 'all':
        self.messagebox = []
      elif option == 'last':
        del self.messagebox[-1]
      else:
        print("You choose the worng option.")
        print("Please choose right option either 'all' or 'last'")


#실제 예시 실행
sam = Messenger('Sam', '010-7777-7777')
peter = Messenger('Peter', '010-9999-1111')

sam.info()
peter.info()

sam.send(peter, "Hello")

peter.read_latest()

peter.send(sam, "What's up?")

sam.read_latest()

for i in range(1, 10):
    peter.send(sam, i)

sam.read_recent(3)

sam.delete('last')
sam.read_recent(3)

sam.delete('last')
sam.delete('last')
sam.read_latest()

sam.delete('all')
sam.read_latest()

sam.read_recent(3)
